### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhemeduogewangtianyi** [nyakaz73/spring-boot-reactjs-fullstack#1]
var path = require('path');

module.exports = {
    entry: './src/main/js/App.js',
    devtool: 'hidden-source-map',
    cache: true,
    mode: 'development',
    output: {
        path: __dirname,
        filename: './src/main/resources/static/built/bundle.js'
    },
    module: {
        rules: [
            {
                test: path.join(__dirname, '.'),
                exclude: /(node_modules)/,
                use: [{
                    loader: 'babel-loader',
                    options: {
                        presets: ["@babel/preset-env", "@babel/preset-react"]
                    }
                }]
            },
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            },
            {
                test: /\.(png|svg|jpg|gif|eot|otf|ttf|woff|woff2)$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: {}
                    }
                ]
            }
        ]
    }
}; 

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.

**Comment by ArchibaldBienetre** [comment]
+1 I have the same issue. 

## When It happens

When running `npm run-script watch --verbose`

## Why it happens

As the message states, this comes with webpack 5. 
  * The example project generates these dependencies in `package.json` (and with these, it works): 
```
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"   
```
  * If I follow the tutorial nowadays, I get this: 
```
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2"
```
 
## Where the issue lies

This line in `webpack.config.js` is invalid:
```
    devtool: 'source-map',
```
** it must be something like "source-maps" instead: 
```
    devtool: 'source-map',
```

## What workarounds / fixes didn't work for me 

* What I tried: 
  * changing `webpack.config.js` without doing anything else 
```
module.exports = {
    entry: './src/main/js/App.js',
    devtool: 'source-map',
```    
  * Update of all dependencies 
```
npm update --depth 5
```
```
npm update
```

## Working workaround

* What works: 
  * Delete the `node_modules` folder
  * Put these versions for the webpack dependencies in `package.json` again:
``` 
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"  
```
* Then running `npm run-script watch --verbose` will work
